### ISSUE TITLE
Support for cdn/node_modules

### ISSUE THREAD

**Issue by shumphrey** [mairatma/babel-plugin-globals#6]
Hello,

I have the following line in a source file:

``` javascript
import Mn from 'backbone.marionette';
```

This is hosted via a CDN for production code and via node_modules for testing purposes.
I would like to handle this statement differently to local source code when using babel-plugin-globals.
I want normal <code>import { MyClass } from '../path/to/my/source'</code> to be handled just as babel-plugin-globals does now, but I want <code>import MyAlreadyGlobal from 'not_a_file_path'</code> to be handled differently.

I experimented with the globalName function I previously added to this module however, this doesn't work.

Firstly, <code>globalName(state, filePath, name, isWildCard)</code> does not get given the node type. I cannot tell if this is an import statement. Nor is it given the string 'Mn'
To reliably handle the already global case I would need to know:
- Is this an import statement?
- is filePath a non-path string
- What is the variable name I'm importing into (e.g. 'Mn')
  If I had the above info, I could make globalName return 

Secondly, even if globalName could return something like 'Mn' this would result in a statement like <code>var Mn = Mn</code> (although I could get around that by just using a different name)

Thirdly <code>filePath</code> for backbone.marionette is 'backbone' as [index.js#L169](https://github.com/mairatma/babel-plugin-globals/blob/master/index.js#L169) strips off the '.marionette'

My aim here is for code to explicitly import everything. This makes testing easier as the testing system can replace the import lines with commonjs which would import from node_modules
I hope this ticket makes sense.

I am open to suggestions on how to do this.
Perhaps another explicit callback for ImportDeclaration, or perhaps my own babel visitor for ImportDeclaration before babel-plugin-globals

**Comment by mairatma** [comment]
I see, you're right, this makes total sense.

I think that your suggestion of doing this inside`ImportDeclaration` would be the way to go. When the import source is not a file path we could simply remove the import declaration entirely, without replacing it with any assignments, always assuming that the global already exists. That way we don't need to change `globalName`, just add the check in `ImportDeclaration` and do the needed work there.

Is this something that you'd have time to contribute with? Unfortunately I currently don't have the time to work on it myself, but if you send a pull request I'll make sure to review it soon. I haven't posted contribution guidelines or anything, since it's a very small project, but if you do this just make sure to follow these before sending the pr:
- Add a test for this use case
- Make sure all tests still pass (you can run them with `npm test`)
- Run `npm run lint` and fix any lint errors

**Comment by shumphrey** [comment]
Sure, I'll submit a PR for this ~monday.
